---
title: "Causal Effect of Data Capture on Retail Sales Analysis"
author: "Michael Brucek, Kevin Grady, Anthony Meyers, Danny Moncada, Jack Quick"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
toc: true
---

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}

library(readr) # reading the data files
library(dplyr) # for data manipulation
library(plm)
library(stargazer) # viewing regression output
library(lmtest)
library(ggplot2) # data visualization
library(Synth) # synthetic control
library(lubridate)
library(scales)
```

# Data Loading, Munging & Exploratory Data Analysis

## Load Data

```{r loading data, message=FALSE, warning=FALSE}

# set the working dir for project files
setwd("C:/Users/danny/Downloads/Causal_Group_Project")

# Original set of data files provided by retailer
stores <- read_csv("stores data-set.csv")
sales <- read_csv("sales data-set.csv")
features <- read_csv("Features data set.csv")

# Data files generated for clustering analysis
stores_agg <- read_csv('store_features.csv')
stores_agg_clusters <- read_csv('store_features_with_cluster.csv')
```

## Data Munging & Feature Generation

```{r, data cleaning}

# Convert Date field in sales from dd/mm/yyyy to yyyy/mm/dd
sales$Date_new <- strptime(as.character(sales$Date), "%d/%m/%Y")
sales$Date <- format(sales$Date_new, "%Y-%m-%d")
sales$Date <- as.Date(sales$Date, format = "%Y-%m-%d")
sales = sales[-c(6)]

# Convert Date field in features from dd/mm/yyyy to yyyy/mm/dd
features$Date_new <- strptime(as.character(features$Date), "%d/%m/%Y")
features$Date <- format(features$Date_new, "%Y-%m-%d")
features$Date <- as.Date(features$Date, format = "%Y-%m-%d")
features = features[-c(13) ]

features <- features %>% filter(!is.na(CPI) | !is.na(Unemployment))

# Get weekly sales for each store
sales_weekly <- sales %>% group_by(Store, Date) %>% 
  summarise(sales = sum(Weekly_Sales), holiday = max(IsHoliday))

# Merge sales and stores to get store size and type
sales_weekly <- merge(sales_weekly, stores, by = "Store")

# Merge sales and featurees to get weekly features for each store
sales_weekly <- merge(sales_weekly, features, by = c("Store", "Date"))

# Create an "after" treatment variable
sales_weekly$after <- ifelse(sales_weekly$Date > '2011-11-04', 1, 0)
```

## Exploratory Data Analysis

```{r, EDA, fig.width = 18, fig.height = 7}

# Aggregate Total Weekly Sales by Date by Store Type into new table sales_weekly_type
sales_weekly_type <- sales_weekly %>% select(Date, sales, Type, holiday) %>% 
  group_by(Date, Type, holiday) %>% 
  filter(holiday == 0) %>%
  summarise(Average_Weekly_Sales = mean(sales), Total_Weekly_Sales = sum(sales))

# All Store Types - Plot of Total Weekly Sales by Date; 
ggplot(sales_weekly_type, aes(x = Date, y = Total_Weekly_Sales/1000, color = Type)) + 
  geom_line(size=1) + 
  geom_vline(xintercept = as.Date('2011-11-11'), linetype='dotted', size=1) + 
  theme_bw() +
  labs(title="Total Weekly Sales by Store Type (excluding holiday weeks)", 
       y="Total Weekly Sales (in 1000s)") +
  scale_x_date(breaks = date_breaks("6 months"),
               labels = date_format("%b-%Y")) +
  geom_smooth(method = 'loess')
```

# Fixed Effects Regression

```{r Fixed Effects}

# Let's try a fixed effect regression.
# Fixed effect for Store
within_reg <- plm(data=sales_weekly, sales ~ as.factor(after) + 
                    Temperature + Fuel_Price + CPI + Unemployment,
                  index=c("Store"),effect="individual",model="within")

pooling_reg <- plm(data=sales_weekly, sales ~ as.factor(after) + 
                     Temperature + Fuel_Price + CPI + Unemployment,
                   index=c("Store"),effect="individual",model="pooling")

ols_reg <-lm(sales ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment , data = sales_weekly)

# Generate summary table for fixed effects regression
stargazer(within_reg, pooling_reg, 
          title="Fixed vs. Pooling Effect Model",
          column.labels = c("Within", "Pooling"), type="text")

# Let's see if panel data model is needed
pFtest(within_reg, pooling_reg)

# Significant effects for Store
```

## Fixed Effects vs Random Effects

```{r Fixed Effect vs Random Effect}

# Fixed Effect vs Random Effect
random_reg = plm(sales ~ as.factor(after) + Temperature + 
                   Fuel_Price + CPI + Unemployment, 
                 data = sales_weekly, index=c("Store"), effect="individual", model="random")

# Generate summary table comparing fixed effect vs random effect
stargazer(within_reg, random_reg, 
          title="Fixed vs. Random Effect Model",
          column.labels = c("Within", "Random"), type="text")

# Hausman test
phtest(within_reg, random_reg)

# Durbin Wu Hausman prefers random effect model

# Serial Correlation (Breusch Godfrey Test)

# Null hypothesis: Random Effect model is more efficient
# With p-value effectively = 0, we reject and conclude that there is serial correlation
pbgtest(random_reg)


# Testing for Hetroskedasticity
bptest(sales ~ as.factor(after) + Temperature + 
         Fuel_Price + CPI + Unemployment + as.factor(Store), 
       data = sales_weekly)

# Heteroskedasticity not present
```


```{r}

random_reg2 <-  plm(log(sales) ~ as.factor(after) + Temperature + 
                      Fuel_Price + CPI + Unemployment, 
                    data = sales_weekly, index=c("Store"), effect="individual", model="random")

# Generate summary table
summary(random_reg2)
```

```{r}
random_reg3 <- plm(log(sales) ~ as.factor(after) + Temperature + 
                     Fuel_Price + CPI, 
                   data = sales_weekly, index=c("Store"), effect="individual", model="random")

# Generate summary table
summary(random_reg3)
```

```{r}

#Testing for Hetroskedasticity
bptest(log(sales) ~ as.factor(after) + Temperature + Fuel_Price + CPI + as.factor(Store), data = sales_weekly)

# Still no heteroskedasticity
```

# Synthetic Control

## Load Data
```{r, Synethic Control Data Loading}

# Pull in our clustered store data, loaded earlier in the analysis
stores_agg_clusters <- stores_agg_clusters %>% select(Store, k4cluster)

# Merge our two data sets together by store
stores_agg <- merge(stores_agg, stores_agg_clusters, by = 'Store')

# Merge our weekly sales data with our cluster data
sales_weekly_cluster <- merge(sales_weekly, stores_agg_clusters, by = 'Store')

# Create a new dataframe by grouping on our four clusters and date
clusters <- sales_weekly_cluster %>% 
  group_by(k4cluster, Date) %>% 
  summarise(tot_sales = sum(sales), # Total weekly sales by cluster
            temp = mean(Temperature), # Average temperature by cluster
            fuel_price = mean(Fuel_Price), # Average fuel price by cluster
            CPI = mean(CPI), # Average Consumer Price Index by cluster
            unemployment = mean(unemployment)) # Average unemployment by cluster
```

## Visualize Weekly Sales by Cluster
```{r, fig.width = 18, fig.height = 7}

# Generate a plot comparing our clusters and their total sales by week... do they 
# behave similarly?
ggplot(clusters) + 
  geom_line(aes(Date, tot_sales/1000, col = as.factor(k4cluster))) + 
  geom_vline(xintercept = as.Date('2011-11-11'), linetype = 'dotted')+ 
  theme_bw() +
  labs(title="Total Weekly Sales by Cluster (excluding holiday weeks)", 
       y="Total Weekly Sales (in 1000s)") +
  scale_x_date(breaks = date_breaks("6 months"),
               labels = date_format("%b-%Y"))
```

## Data Prep
```{r, data prep, message=FALSE, warning=FALSE}

# Read in modeling features data set created for Synthetic control analysis
modeling_features <- read_csv('modeling_features_mb1.csv')

# Subset the CSV file to only include the columns that we need
modeling_features <- modeling_features %>% 
              select(week, k4cluster, total_weekly_sales, avg_weekly_sales,
                     total_markdown_count, mean_markdown_count_per_store,
                     total_markdown_sum, mean_markdown_sum_per_store,
                     avg_temp, avg_CPI, avg_unemployment, avg_fuel_price)

# Convert the k4cluster to a numeric value so that it can be used by Synth package
modeling_features$k4cluster <- as.numeric(modeling_features$k4cluster)

# Rename the total_weekly_sales column to Y so that we can actually use this in Synth package
modeling_features$Y <- modeling_features$total_weekly_sales/1000

# Generate a new column with a character field for cluster, again for Synth package
modeling_features$cluster <- ifelse(modeling_features$k4cluster == 1, 'One', 
                                    ifelse(modeling_features$k4cluster == 2, 'Two', 
                                           ifelse(modeling_features$k4cluster == 3, 'Three', 'Four')))

# Convert to data frame for Synth package
modeling_features <- as.data.frame(modeling_features)

# View a sample of the data table
head(modeling_features[c("week", "cluster", "Y", "avg_temp", "avg_CPI")])
```


## Analysis
```{r - Synthetic Control Analysis}

# Outcome variable *must* be named Y for Synth to accept it
dataprep.out=
   dataprep(foo = modeling_features,
   predictors = c("total_markdown_count", "mean_markdown_count_per_store",
                  "total_markdown_sum", "mean_markdown_sum_per_store",
                  "avg_temp","avg_CPI","avg_unemployment","avg_fuel_price"),
   predictors.op = "mean",
   dependent = "Y",
   unit.variable = "k4cluster",
   time.variable = "week",
   
   # Which panel is treated?
   # Cluster 1
   treatment.identifier = 1,
   
   # Which panels are we using to construct the synthetic control?
   # The remaining clusters
   controls.identifier = c(2,3,4),
   
   ## What is the pre-treatment time period?
   ## Weeks 1-93 were before markdown was captured
   time.predictors.prior = c(1:93),
   
   # The whole time frame of data, from weeks 1 through the data
   time.optimize.ssr = c(1:143),
   
   # Name of panel units
   unit.names.variable = "cluster",
   
   # Time period to generate the plot for (all weeks)
   time.plot = c(1:143))

# Output the data
synth.out = synth(dataprep.out)
```

## Visualization

```{r, Plotting the Outcomes of Synthetic Control, fig.width = 15, fig.height = 7}
path.plot(dataprep.res = dataprep.out, synth.res = synth.out,
          Xlab="Week", Ylab="Total Weekly Sales (1000s)",
          Main="Comparison of Synthetic vs. Actual Total Weekly Sales")

abline(v=93,lty=2,col="blue")
```