---
title: "Difference in Difference"
author: "Jack Quick"
date: "April 19, 2020"
output: pdf_document
---

```{r libraries}

## Suppress warnings for loading packages
suppressWarnings(suppressPackageStartupMessages({
library(readr)
library(dplyr)
library(plm)
library(stargazer)
library(lmtest)
library(ggplot2)
library(Synth)
library(lubridate)
}))
```

```{r}

## set the working dir for project files
setwd("C:/Users/danny/Downloads/Causal_Group_Project")
## insert your working dir here

# To be used if we want to somehow implement cluster
stores_agg <- read_csv('store_features.csv')
stores_agg_clusters <- read_csv('store_features_with_cluster.csv')

stores <- read_csv("stores data-set.csv")
sales <- read_csv("sales data-set.csv")
features <- read_csv("Features data set.csv")

```

```{r}

# Convert Date field in sales from dd/mm/yyyy to yyyy/mm/dd
sales$Date_new <- strptime(as.character(sales$Date), "%d/%m/%Y")
sales$Date <- format(sales$Date_new, "%Y-%m-%d")
sales$Date <- as.Date(sales$Date, format = "%Y-%m-%d")
sales = sales[-c(6) ]

# Convert Date field in features from dd/mm/yyyy to yyyy/mm/dd
features$Date_new <- strptime(as.character(features$Date), "%d/%m/%Y")
features$Date <- format(features$Date_new, "%Y-%m-%d")
features$Date <- as.Date(features$Date, format = "%Y-%m-%d")
features = features[-c(13) ]

features <- features %>% filter(!is.na(CPI) | !is.na(Unemployment))

```

```{r}

# Get weekly sale for each store
sales_weekly <- sales %>% group_by(Store, Date) %>% summarise(sales = sum(Weekly_Sales), holiday = max(IsHoliday))

# Merge sales and stores to get store size and type
sales_weekly <- merge(sales_weekly, stores, by = "Store")

# Merge sales and featurees to get weekly features for each store

sales_weekly <- merge(sales_weekly, features, by = c("Store", "Date"))

sales_weekly$after <- ifelse(sales_weekly$Date > '2011-11-04', 1, 0)

```

```{r Fixed Effects}

# Let's try a fixed effect regression.   

# Fixed effect for Store

within_reg <- plm(data=sales_weekly, sales ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment ,index=c("Store"),effect="individual",model="within")

pooling_reg <- plm(data=sales_weekly, sales ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment,index=c("Store"),effect="individual",model="pooling")

ols_reg <-lm(sales ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment , data = sales_weekly)

stargazer(within_reg, pooling_reg, title="Fixed vs. Pooling Effect Model",column.labels = c("Within", "Pooling"), type="text")

#Let's see if panel data model is needed

pFtest(within_reg, pooling_reg)

# Significant effects for Store (?)

# Fixed Effect vs Random Effect

random_reg = plm(sales ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment, data = sales_weekly, index=c("Store"), effect="individual", model="random")

stargazer(within_reg, random_reg, title="Fixed vs. Random Effect Model",column.labels = c("Within", "Random"), type="text")


# Hausman test
phtest(within_reg, random_reg)

# Durbin Wu Hausman prefers random effect model

# Serial Correlation (Breusch Godfrey Test)

# Null hypothesis: Random Effect model is more efficient
# With p-value effectively = 0, we reject and conclude that there is serial correlation

pbgtest(random_reg)


#Testing for Hetroskedasticity

bptest(sales ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment + as.factor(Store), data = sales_weekly)

# Heteroskedasticity not present

```


```{r}

random_reg2 <-  plm(log(sales) ~ as.factor(after) + Temperature + Fuel_Price + CPI + Unemployment, data = sales_weekly, index=c("Store"), effect="individual", model="random")

summary(random_reg2)

```

```{r}
random_reg3 <- plm(log(sales) ~ as.factor(after) + Temperature + Fuel_Price + CPI, data = sales_weekly, index=c("Store"), effect="individual", model="random")

summary(random_reg3)

```


```{r}

#Testing for Hetroskedasticity

bptest(log(sales) ~ as.factor(after) + Temperature + Fuel_Price + CPI + as.factor(Store), data = sales_weekly)

# Still no heteroskedasticity

```

# SYNTHETIC CONTROL

```{r}

stores_agg_clusters <- stores_agg_clusters %>% select(Store, k4cluster)

stores_agg <- merge(stores_agg, stores_agg_clusters, by = 'Store')

```

```{r}

sales_weekly_cluster <- merge(sales_weekly, stores_agg_clusters, by = 'Store')

```

```{r}

clusters <- sales_weekly_cluster %>% group_by(k4cluster, Date) %>% summarise(tot_sales = sum(sales), temp = mean(Temperature), fuel_price = mean(Fuel_Price), CPI = mean(CPI), unemployment = mean(unemployment))

```

```{r}

# Got our four clusters and their total sales over time, are they behaving similarly?
# Nope

# Using Cluster 1 as our cluster of interest
# Why? Because Stone Cold said so

ggplot(clusters) + geom_line(aes(Date, tot_sales, col = as.factor(k4cluster))) + geom_vline(xintercept = as.Date('2011-11-11'), linetype = 'dotted')

```

### Synthetic Control Code

```{r - data prep for Synthetic Control analysis}

## Read in modeling features data set created for Synthetic control analysis
modeling_features <- read_csv('modeling_features_mb1.csv')

## Subset the CSV file to only include the columns that we need
modeling_features <- modeling_features %>% 
              select(week, k4cluster, total_weekly_sales, avg_weekly_sales,
                     total_markdown_count, mean_markdown_count_per_store,
                     total_markdown_sum, mean_markdown_sum_per_store,
                     avg_temp, avg_CPI, avg_unemployment, avg_fuel_price)

## Convert the k4cluster to a numeric value so that it can be used by Synth package.
modeling_features$k4cluster <- as.numeric(modeling_features$k4cluster)

## Rename the total_weekly_sales column to Y so that we can actually use this in Synth package.
modeling_features <- modeling_features %>% rename(Y = total_weekly_sales)
# modeling_features <- modeling_features %>% rename(Y = avg_weekly_sales) # if we want to run using avg. weekly sales.

## Generate a new column with a character field for cluster, again for Synth package.
modeling_features$cluster <- ifelse(modeling_features$k4cluster == 1, 'One', 
                                    ifelse(modeling_features$k4cluster == 2, 'Two', 
                                           ifelse(modeling_features$k4cluster == 3, 'Three', 'Four')))

## Convert to data frame for Synth package.
modeling_features <- as.data.frame(modeling_features)

## Confirm our data manipulation was successful.
head(modeling_features)

```

```{r - Synthetic Control Analysis}
#your outcome variable *must* be named Y for Synth to accept it

dataprep.out=
   dataprep(foo = modeling_features1,
   predictors = c("total_markdown_count", "mean_markdown_count_per_store",
                  "total_markdown_sum", "mean_markdown_sum_per_store",
                  "avg_temp","avg_CPI","avg_unemployment","avg_fuel_price"),
   predictors.op = "mean",
   dependent = "Y",
   unit.variable = "k4cluster",
   time.variable = "week",
   
   #Any pre-period X's we want to include using different aggregation function, other than mean, or different
   #time windows, specific years vs. all years, we enter here.
   
   
   ## which panel is treated?
   treatment.identifier = 1,
   
   ## which panels are we using to construct the synthetic control?
   controls.identifier = c(2,3,4),
   
   ## what is the pre-treatment time period?
   ## Weeks 1-93 were before markdown was captured
   time.predictors.prior = c(1:93),
   
   ## The whole time frame of data, from weeks 1 through the data
   time.optimize.ssr = c(1:143),
   
   ## name of panel units
   unit.names.variable = "cluster",
   
   ## time period to generate the plot for.
   time.plot = c(1:143))

## Output the data
synth.out = synth(dataprep.out)

```

```{r, Plotting the Outcomes of Synthetic Control, fig.width = 15, fig.height = 10}
path.plot(dataprep.res = dataprep.out, synth.res = synth.out,Xlab="Week",

Ylab="Average Weekly Sales",
Main="Comparison of Synth vs. Actual Per Weekly Sales")

abline(v=93,lty=2,col="blue")
```
